// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.serialization.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GraphTopology extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static GraphTopology getRootAsGraphTopology(ByteBuffer _bb) { return getRootAsGraphTopology(_bb, new GraphTopology()); }
  public static GraphTopology getRootAsGraphTopology(ByteBuffer _bb, GraphTopology obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GraphTopology __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int nodeCount() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int edgeCount() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int firstEdge(int j) { int o = __offset(8); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int firstEdgeLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public IntVector firstEdgeVector() { return firstEdgeVector(new IntVector()); }
  public IntVector firstEdgeVector(IntVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer firstEdgeAsByteBuffer() { return __vector_as_bytebuffer(8, 4); }
  public ByteBuffer firstEdgeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 4); }
  public int edgeTarget(int j) { int o = __offset(10); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int edgeTargetLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public IntVector edgeTargetVector() { return edgeTargetVector(new IntVector()); }
  public IntVector edgeTargetVector(IntVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer edgeTargetAsByteBuffer() { return __vector_as_bytebuffer(10, 4); }
  public ByteBuffer edgeTargetInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 4); }
  public org.Aayush.serialization.flatbuffers.taro.model.Coordinate coordinates(int j) { return coordinates(new org.Aayush.serialization.flatbuffers.taro.model.Coordinate(), j); }
  public org.Aayush.serialization.flatbuffers.taro.model.Coordinate coordinates(org.Aayush.serialization.flatbuffers.taro.model.Coordinate obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int coordinatesLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public org.Aayush.serialization.flatbuffers.taro.model.Coordinate.Vector coordinatesVector() { return coordinatesVector(new org.Aayush.serialization.flatbuffers.taro.model.Coordinate.Vector()); }
  public org.Aayush.serialization.flatbuffers.taro.model.Coordinate.Vector coordinatesVector(org.Aayush.serialization.flatbuffers.taro.model.Coordinate.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public float baseWeights(int j) { int o = __offset(14); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int baseWeightsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector baseWeightsVector() { return baseWeightsVector(new FloatVector()); }
  public FloatVector baseWeightsVector(FloatVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer baseWeightsAsByteBuffer() { return __vector_as_bytebuffer(14, 4); }
  public ByteBuffer baseWeightsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 4); }
  public int edgeProfileId(int j) { int o = __offset(16); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int edgeProfileIdLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector edgeProfileIdVector() { return edgeProfileIdVector(new ShortVector()); }
  public ShortVector edgeProfileIdVector(ShortVector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer edgeProfileIdAsByteBuffer() { return __vector_as_bytebuffer(16, 2); }
  public ByteBuffer edgeProfileIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 2); }
  public int edgeFlags(int j) { int o = __offset(18); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int edgeFlagsLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector edgeFlagsVector() { return edgeFlagsVector(new ByteVector()); }
  public ByteVector edgeFlagsVector(ByteVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer edgeFlagsAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer edgeFlagsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public int edgeOrigin(int j) { int o = __offset(20); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int edgeOriginLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public IntVector edgeOriginVector() { return edgeOriginVector(new IntVector()); }
  public IntVector edgeOriginVector(IntVector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer edgeOriginAsByteBuffer() { return __vector_as_bytebuffer(20, 4); }
  public ByteBuffer edgeOriginInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 4); }

  public static int createGraphTopology(FlatBufferBuilder builder,
      int nodeCount,
      int edgeCount,
      int firstEdgeOffset,
      int edgeTargetOffset,
      int coordinatesOffset,
      int baseWeightsOffset,
      int edgeProfileIdOffset,
      int edgeFlagsOffset,
      int edgeOriginOffset) {
    builder.startTable(9);
    GraphTopology.addEdgeOrigin(builder, edgeOriginOffset);
    GraphTopology.addEdgeFlags(builder, edgeFlagsOffset);
    GraphTopology.addEdgeProfileId(builder, edgeProfileIdOffset);
    GraphTopology.addBaseWeights(builder, baseWeightsOffset);
    GraphTopology.addCoordinates(builder, coordinatesOffset);
    GraphTopology.addEdgeTarget(builder, edgeTargetOffset);
    GraphTopology.addFirstEdge(builder, firstEdgeOffset);
    GraphTopology.addEdgeCount(builder, edgeCount);
    GraphTopology.addNodeCount(builder, nodeCount);
    return GraphTopology.endGraphTopology(builder);
  }

  public static void startGraphTopology(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addNodeCount(FlatBufferBuilder builder, int nodeCount) { builder.addInt(0, nodeCount, 0); }
  public static void addEdgeCount(FlatBufferBuilder builder, int edgeCount) { builder.addInt(1, edgeCount, 0); }
  public static void addFirstEdge(FlatBufferBuilder builder, int firstEdgeOffset) { builder.addOffset(2, firstEdgeOffset, 0); }
  public static int createFirstEdgeVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startFirstEdgeVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEdgeTarget(FlatBufferBuilder builder, int edgeTargetOffset) { builder.addOffset(3, edgeTargetOffset, 0); }
  public static int createEdgeTargetVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startEdgeTargetVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addCoordinates(FlatBufferBuilder builder, int coordinatesOffset) { builder.addOffset(4, coordinatesOffset, 0); }
  public static void startCoordinatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 16); }
  public static void addBaseWeights(FlatBufferBuilder builder, int baseWeightsOffset) { builder.addOffset(5, baseWeightsOffset, 0); }
  public static int createBaseWeightsVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startBaseWeightsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addEdgeProfileId(FlatBufferBuilder builder, int edgeProfileIdOffset) { builder.addOffset(6, edgeProfileIdOffset, 0); }
  public static int createEdgeProfileIdVector(FlatBufferBuilder builder, int[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort((short) data[i]); return builder.endVector(); }
  public static void startEdgeProfileIdVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addEdgeFlags(FlatBufferBuilder builder, int edgeFlagsOffset) { builder.addOffset(7, edgeFlagsOffset, 0); }
  public static int createEdgeFlagsVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createEdgeFlagsVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startEdgeFlagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addEdgeOrigin(FlatBufferBuilder builder, int edgeOriginOffset) { builder.addOffset(8, edgeOriginOffset, 0); }
  public static int createEdgeOriginVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startEdgeOriginVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endGraphTopology(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GraphTopology get(int j) { return get(new GraphTopology(), j); }
    public GraphTopology get(GraphTopology obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

