// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.serialization.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IdMapping extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static IdMapping getRootAsIdMapping(ByteBuffer _bb) { return getRootAsIdMapping(_bb, new IdMapping()); }
  public static IdMapping getRootAsIdMapping(ByteBuffer _bb, IdMapping obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public IdMapping __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long externalIds(int j) { int o = __offset(4); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int externalIdsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public LongVector externalIdsVector() { return externalIdsVector(new LongVector()); }
  public LongVector externalIdsVector(LongVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer externalIdsAsByteBuffer() { return __vector_as_bytebuffer(4, 8); }
  public ByteBuffer externalIdsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 8); }
  public String externalStringIds(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int externalStringIdsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector externalStringIdsVector() { return externalStringIdsVector(new StringVector()); }
  public StringVector externalStringIdsVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createIdMapping(FlatBufferBuilder builder,
      int externalIdsOffset,
      int externalStringIdsOffset) {
    builder.startTable(2);
    IdMapping.addExternalStringIds(builder, externalStringIdsOffset);
    IdMapping.addExternalIds(builder, externalIdsOffset);
    return IdMapping.endIdMapping(builder);
  }

  public static void startIdMapping(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addExternalIds(FlatBufferBuilder builder, int externalIdsOffset) { builder.addOffset(0, externalIdsOffset, 0); }
  public static int createExternalIdsVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startExternalIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addExternalStringIds(FlatBufferBuilder builder, int externalStringIdsOffset) { builder.addOffset(1, externalStringIdsOffset, 0); }
  public static int createExternalStringIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startExternalStringIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endIdMapping(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public IdMapping get(int j) { return get(new IdMapping(), j); }
    public IdMapping get(IdMapping obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

