// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.serialization.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Landmark extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static Landmark getRootAsLandmark(ByteBuffer _bb) { return getRootAsLandmark(_bb, new Landmark()); }
  public static Landmark getRootAsLandmark(ByteBuffer _bb, Landmark obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Landmark __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int nodeIdx() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public float forwardDistances(int j) { int o = __offset(6); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int forwardDistancesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector forwardDistancesVector() { return forwardDistancesVector(new FloatVector()); }
  public FloatVector forwardDistancesVector(FloatVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer forwardDistancesAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer forwardDistancesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }
  public float backwardDistances(int j) { int o = __offset(8); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int backwardDistancesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector backwardDistancesVector() { return backwardDistancesVector(new FloatVector()); }
  public FloatVector backwardDistancesVector(FloatVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer backwardDistancesAsByteBuffer() { return __vector_as_bytebuffer(8, 4); }
  public ByteBuffer backwardDistancesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 4); }

  public static int createLandmark(FlatBufferBuilder builder,
      int nodeIdx,
      int forwardDistancesOffset,
      int backwardDistancesOffset) {
    builder.startTable(3);
    Landmark.addBackwardDistances(builder, backwardDistancesOffset);
    Landmark.addForwardDistances(builder, forwardDistancesOffset);
    Landmark.addNodeIdx(builder, nodeIdx);
    return Landmark.endLandmark(builder);
  }

  public static void startLandmark(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNodeIdx(FlatBufferBuilder builder, int nodeIdx) { builder.addInt(0, nodeIdx, 0); }
  public static void addForwardDistances(FlatBufferBuilder builder, int forwardDistancesOffset) { builder.addOffset(1, forwardDistancesOffset, 0); }
  public static int createForwardDistancesVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startForwardDistancesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addBackwardDistances(FlatBufferBuilder builder, int backwardDistancesOffset) { builder.addOffset(2, backwardDistancesOffset, 0); }
  public static int createBackwardDistancesVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startBackwardDistancesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endLandmark(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Landmark get(int j) { return get(new Landmark(), j); }
    public Landmark get(Landmark obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

