// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.serialization.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TemporalProfile extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static TemporalProfile getRootAsTemporalProfile(ByteBuffer _bb) { return getRootAsTemporalProfile(_bb, new TemporalProfile()); }
  public static TemporalProfile getRootAsTemporalProfile(ByteBuffer _bb, TemporalProfile obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TemporalProfile __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int profileId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int dayMask() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public float buckets(int j) { int o = __offset(8); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int bucketsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector bucketsVector() { return bucketsVector(new FloatVector()); }
  public FloatVector bucketsVector(FloatVector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer bucketsAsByteBuffer() { return __vector_as_bytebuffer(8, 4); }
  public ByteBuffer bucketsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 4); }
  public float multiplier() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f; }

  public static int createTemporalProfile(FlatBufferBuilder builder,
      int profileId,
      int dayMask,
      int bucketsOffset,
      float multiplier) {
    builder.startTable(4);
    TemporalProfile.addMultiplier(builder, multiplier);
    TemporalProfile.addBuckets(builder, bucketsOffset);
    TemporalProfile.addProfileId(builder, profileId);
    TemporalProfile.addDayMask(builder, dayMask);
    return TemporalProfile.endTemporalProfile(builder);
  }

  public static void startTemporalProfile(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addProfileId(FlatBufferBuilder builder, int profileId) { builder.addShort(0, (short) profileId, (short) 0); }
  public static void addDayMask(FlatBufferBuilder builder, int dayMask) { builder.addByte(1, (byte) dayMask, (byte) 0); }
  public static void addBuckets(FlatBufferBuilder builder, int bucketsOffset) { builder.addOffset(2, bucketsOffset, 0); }
  public static int createBucketsVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startBucketsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMultiplier(FlatBufferBuilder builder, float multiplier) { builder.addFloat(3, multiplier, 1.0f); }
  public static int endTemporalProfile(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TemporalProfile get(int j) { return get(new TemporalProfile(), j); }
    public TemporalProfile get(TemporalProfile obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

