// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.serialization.flatbuffers.taro.model;

@SuppressWarnings("unused")
public final class TimeUnit {
  private TimeUnit() { }
  public static final int SECONDS = 0;
  public static final int MILLISECONDS = 1;

  public static final String[] names = { "SECONDS", "MILLISECONDS", };

  public static String name(int e) { return names[e]; }
}

