// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.serialization.flatbuffers.taro.model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TurnCost extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static TurnCost getRootAsTurnCost(ByteBuffer _bb) { return getRootAsTurnCost(_bb, new TurnCost()); }
  public static TurnCost getRootAsTurnCost(ByteBuffer _bb, TurnCost obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TurnCost __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int fromEdgeIdx() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int toEdgeIdx() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public float penaltySeconds() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createTurnCost(FlatBufferBuilder builder,
      int fromEdgeIdx,
      int toEdgeIdx,
      float penaltySeconds) {
    builder.startTable(3);
    TurnCost.addPenaltySeconds(builder, penaltySeconds);
    TurnCost.addToEdgeIdx(builder, toEdgeIdx);
    TurnCost.addFromEdgeIdx(builder, fromEdgeIdx);
    return TurnCost.endTurnCost(builder);
  }

  public static void startTurnCost(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addFromEdgeIdx(FlatBufferBuilder builder, int fromEdgeIdx) { builder.addInt(0, fromEdgeIdx, 0); }
  public static void addToEdgeIdx(FlatBufferBuilder builder, int toEdgeIdx) { builder.addInt(1, toEdgeIdx, 0); }
  public static void addPenaltySeconds(FlatBufferBuilder builder, float penaltySeconds) { builder.addFloat(2, penaltySeconds, 0.0f); }
  public static int endTurnCost(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TurnCost get(int j) { return get(new TurnCost(), j); }
    public TurnCost get(TurnCost obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}
