# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GraphTopology(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GraphTopology()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGraphTopology(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GraphTopologyBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # GraphTopology
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GraphTopology
    def NodeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphTopology
    def EdgeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphTopology
    def FirstEdge(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def FirstEdgeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphTopology
    def FirstEdgeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def FirstEdgeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GraphTopology
    def EdgeTarget(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def EdgeTargetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphTopology
    def EdgeTargetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeTargetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # GraphTopology
    def Coordinates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from taro.model.Coordinate import Coordinate
            obj = Coordinate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GraphTopology
    def CoordinatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def CoordinatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # GraphTopology
    def BaseWeights(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def BaseWeightsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # GraphTopology
    def BaseWeightsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def BaseWeightsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # GraphTopology
    def EdgeProfileId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # GraphTopology
    def EdgeProfileIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # GraphTopology
    def EdgeProfileIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeProfileIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # GraphTopology
    def EdgeFlags(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # GraphTopology
    def EdgeFlagsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # GraphTopology
    def EdgeFlagsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeFlagsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # GraphTopology
    def EdgeOrigin(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def EdgeOriginAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphTopology
    def EdgeOriginLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeOriginIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def GraphTopologyStart(builder):
    builder.StartObject(9)

def Start(builder):
    GraphTopologyStart(builder)

def GraphTopologyAddNodeCount(builder, nodeCount):
    builder.PrependInt32Slot(0, nodeCount, 0)

def AddNodeCount(builder, nodeCount):
    GraphTopologyAddNodeCount(builder, nodeCount)

def GraphTopologyAddEdgeCount(builder, edgeCount):
    builder.PrependInt32Slot(1, edgeCount, 0)

def AddEdgeCount(builder, edgeCount):
    GraphTopologyAddEdgeCount(builder, edgeCount)

def GraphTopologyAddFirstEdge(builder, firstEdge):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(firstEdge), 0)

def AddFirstEdge(builder, firstEdge):
    GraphTopologyAddFirstEdge(builder, firstEdge)

def GraphTopologyStartFirstEdgeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFirstEdgeVector(builder, numElems):
    return GraphTopologyStartFirstEdgeVector(builder, numElems)

def GraphTopologyCreateFirstEdgeVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependInt32(item)
    return builder.EndVector()

def CreateFirstEdgeVector(builder, data):
    GraphTopologyCreateFirstEdgeVector(builder, data)

def GraphTopologyAddEdgeTarget(builder, edgeTarget):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edgeTarget), 0)

def AddEdgeTarget(builder, edgeTarget):
    GraphTopologyAddEdgeTarget(builder, edgeTarget)

def GraphTopologyStartEdgeTargetVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdgeTargetVector(builder, numElems):
    return GraphTopologyStartEdgeTargetVector(builder, numElems)

def GraphTopologyCreateEdgeTargetVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependInt32(item)
    return builder.EndVector()

def CreateEdgeTargetVector(builder, data):
    GraphTopologyCreateEdgeTargetVector(builder, data)

def GraphTopologyAddCoordinates(builder, coordinates):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(coordinates), 0)

def AddCoordinates(builder, coordinates):
    GraphTopologyAddCoordinates(builder, coordinates)

def GraphTopologyStartCoordinatesVector(builder, numElems):
    return builder.StartVector(16, numElems, 16)

def StartCoordinatesVector(builder, numElems):
    return GraphTopologyStartCoordinatesVector(builder, numElems)

def GraphTopologyCreateCoordinatesVector(builder, data):
    data = list(data)
    builder.StartVector(16, len(data), 16)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateCoordinatesVector(builder, data):
    GraphTopologyCreateCoordinatesVector(builder, data)

def GraphTopologyAddBaseWeights(builder, baseWeights):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(baseWeights), 0)

def AddBaseWeights(builder, baseWeights):
    GraphTopologyAddBaseWeights(builder, baseWeights)

def GraphTopologyStartBaseWeightsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBaseWeightsVector(builder, numElems):
    return GraphTopologyStartBaseWeightsVector(builder, numElems)

def GraphTopologyCreateBaseWeightsVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependFloat32(item)
    return builder.EndVector()

def CreateBaseWeightsVector(builder, data):
    GraphTopologyCreateBaseWeightsVector(builder, data)

def GraphTopologyAddEdgeProfileId(builder, edgeProfileId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(edgeProfileId), 0)

def AddEdgeProfileId(builder, edgeProfileId):
    GraphTopologyAddEdgeProfileId(builder, edgeProfileId)

def GraphTopologyStartEdgeProfileIdVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartEdgeProfileIdVector(builder, numElems):
    return GraphTopologyStartEdgeProfileIdVector(builder, numElems)

def GraphTopologyCreateEdgeProfileIdVector(builder, data):
    data = list(data)
    builder.StartVector(2, len(data), 2)
    for item in reversed(data):
        builder.PrependUint16(item)
    return builder.EndVector()

def CreateEdgeProfileIdVector(builder, data):
    GraphTopologyCreateEdgeProfileIdVector(builder, data)

def GraphTopologyAddEdgeFlags(builder, edgeFlags):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(edgeFlags), 0)

def AddEdgeFlags(builder, edgeFlags):
    GraphTopologyAddEdgeFlags(builder, edgeFlags)

def GraphTopologyStartEdgeFlagsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartEdgeFlagsVector(builder, numElems):
    return GraphTopologyStartEdgeFlagsVector(builder, numElems)

def GraphTopologyCreateEdgeFlagsVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateEdgeFlagsVector(builder, data):
    GraphTopologyCreateEdgeFlagsVector(builder, data)

def GraphTopologyAddEdgeOrigin(builder, edgeOrigin):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(edgeOrigin), 0)

def AddEdgeOrigin(builder, edgeOrigin):
    GraphTopologyAddEdgeOrigin(builder, edgeOrigin)

def GraphTopologyStartEdgeOriginVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdgeOriginVector(builder, numElems):
    return GraphTopologyStartEdgeOriginVector(builder, numElems)

def GraphTopologyCreateEdgeOriginVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependInt32(item)
    return builder.EndVector()

def CreateEdgeOriginVector(builder, data):
    GraphTopologyCreateEdgeOriginVector(builder, data)

def GraphTopologyEnd(builder):
    return builder.EndObject()

def End(builder):
    return GraphTopologyEnd(builder)
