# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GraphTopology(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GraphTopology()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGraphTopology(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GraphTopologyBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # GraphTopology
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GraphTopology
    def NodeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphTopology
    def EdgeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphTopology
    def FirstEdge(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def FirstEdgeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphTopology
    def FirstEdgeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def FirstEdgeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GraphTopology
    def EdgeTarget(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def EdgeTargetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphTopology
    def EdgeTargetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeTargetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # GraphTopology
    def Coordinates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from taro.model.Coordinate import Coordinate
            obj = Coordinate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GraphTopology
    def CoordinatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def CoordinatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # GraphTopology
    def BaseWeights(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphTopology
    def BaseWeightsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # GraphTopology
    def BaseWeightsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def BaseWeightsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # GraphTopology
    def EdgeProfileId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # GraphTopology
    def EdgeProfileIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # GraphTopology
    def EdgeProfileIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeProfileIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # GraphTopology
    def EdgeFlags(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # GraphTopology
    def EdgeFlagsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # GraphTopology
    def EdgeFlagsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphTopology
    def EdgeFlagsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def GraphTopologyStart(builder): builder.StartObject(8)
def Start(builder):
    return GraphTopologyStart(builder)
def GraphTopologyAddNodeCount(builder, nodeCount): builder.PrependInt32Slot(0, nodeCount, 0)
def AddNodeCount(builder, nodeCount):
    return GraphTopologyAddNodeCount(builder, nodeCount)
def GraphTopologyAddEdgeCount(builder, edgeCount): builder.PrependInt32Slot(1, edgeCount, 0)
def AddEdgeCount(builder, edgeCount):
    return GraphTopologyAddEdgeCount(builder, edgeCount)
def GraphTopologyAddFirstEdge(builder, firstEdge): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(firstEdge), 0)
def AddFirstEdge(builder, firstEdge):
    return GraphTopologyAddFirstEdge(builder, firstEdge)
def GraphTopologyStartFirstEdgeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartFirstEdgeVector(builder, numElems):
    return GraphTopologyStartFirstEdgeVector(builder, numElems)
def GraphTopologyAddEdgeTarget(builder, edgeTarget): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edgeTarget), 0)
def AddEdgeTarget(builder, edgeTarget):
    return GraphTopologyAddEdgeTarget(builder, edgeTarget)
def GraphTopologyStartEdgeTargetVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEdgeTargetVector(builder, numElems):
    return GraphTopologyStartEdgeTargetVector(builder, numElems)
def GraphTopologyAddCoordinates(builder, coordinates): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(coordinates), 0)
def AddCoordinates(builder, coordinates):
    return GraphTopologyAddCoordinates(builder, coordinates)
def GraphTopologyStartCoordinatesVector(builder, numElems): return builder.StartVector(16, numElems, 16)
def StartCoordinatesVector(builder, numElems):
    return GraphTopologyStartCoordinatesVector(builder, numElems)
def GraphTopologyAddBaseWeights(builder, baseWeights): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(baseWeights), 0)
def AddBaseWeights(builder, baseWeights):
    return GraphTopologyAddBaseWeights(builder, baseWeights)
def GraphTopologyStartBaseWeightsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBaseWeightsVector(builder, numElems):
    return GraphTopologyStartBaseWeightsVector(builder, numElems)
def GraphTopologyAddEdgeProfileId(builder, edgeProfileId): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(edgeProfileId), 0)
def AddEdgeProfileId(builder, edgeProfileId):
    return GraphTopologyAddEdgeProfileId(builder, edgeProfileId)
def GraphTopologyStartEdgeProfileIdVector(builder, numElems): return builder.StartVector(2, numElems, 2)
def StartEdgeProfileIdVector(builder, numElems):
    return GraphTopologyStartEdgeProfileIdVector(builder, numElems)
def GraphTopologyAddEdgeFlags(builder, edgeFlags): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(edgeFlags), 0)
def AddEdgeFlags(builder, edgeFlags):
    return GraphTopologyAddEdgeFlags(builder, edgeFlags)
def GraphTopologyStartEdgeFlagsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartEdgeFlagsVector(builder, numElems):
    return GraphTopologyStartEdgeFlagsVector(builder, numElems)
def GraphTopologyEnd(builder): return builder.EndObject()
def End(builder):
    return GraphTopologyEnd(builder)