# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdMapping(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdMapping()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdMapping(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IdMappingBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # IdMapping
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdMapping
    def ExternalIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # IdMapping
    def ExternalIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # IdMapping
    def ExternalIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IdMapping
    def ExternalIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # IdMapping
    def ExternalStringIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # IdMapping
    def ExternalStringIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IdMapping
    def ExternalStringIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def IdMappingStart(builder): builder.StartObject(2)
def Start(builder):
    return IdMappingStart(builder)
def IdMappingAddExternalIds(builder, externalIds): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(externalIds), 0)
def AddExternalIds(builder, externalIds):
    return IdMappingAddExternalIds(builder, externalIds)
def IdMappingStartExternalIdsVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def StartExternalIdsVector(builder, numElems):
    return IdMappingStartExternalIdsVector(builder, numElems)
def IdMappingAddExternalStringIds(builder, externalStringIds): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(externalStringIds), 0)
def AddExternalStringIds(builder, externalStringIds):
    return IdMappingAddExternalStringIds(builder, externalStringIds)
def IdMappingStartExternalStringIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartExternalStringIdsVector(builder, numElems):
    return IdMappingStartExternalStringIdsVector(builder, numElems)
def IdMappingEnd(builder): return builder.EndObject()
def End(builder):
    return IdMappingEnd(builder)