# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KDNode(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 20

    # KDNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KDNode
    def SplitValue(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # KDNode
    def LeftChild(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # KDNode
    def RightChild(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # KDNode
    def ItemStartIndex(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # KDNode
    def ItemCount(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # KDNode
    def SplitAxis(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(18))
    # KDNode
    def IsLeaf(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(19))

def CreateKDNode(builder, splitValue, leftChild, rightChild, itemStartIndex, itemCount, splitAxis, isLeaf):
    builder.Prep(4, 20)
    builder.PrependUint8(isLeaf)
    builder.PrependUint8(splitAxis)
    builder.PrependUint16(itemCount)
    builder.PrependInt32(itemStartIndex)
    builder.PrependInt32(rightChild)
    builder.PrependInt32(leftChild)
    builder.PrependFloat32(splitValue)
    return builder.Offset()
