# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Landmark(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Landmark()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLandmark(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LandmarkBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # Landmark
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Landmark
    def NodeIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Landmark
    def ForwardDistances(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Landmark
    def ForwardDistancesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Landmark
    def ForwardDistancesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Landmark
    def ForwardDistancesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Landmark
    def BackwardDistances(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Landmark
    def BackwardDistancesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Landmark
    def BackwardDistancesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Landmark
    def BackwardDistancesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def LandmarkStart(builder): builder.StartObject(3)
def Start(builder):
    return LandmarkStart(builder)
def LandmarkAddNodeIdx(builder, nodeIdx): builder.PrependInt32Slot(0, nodeIdx, 0)
def AddNodeIdx(builder, nodeIdx):
    return LandmarkAddNodeIdx(builder, nodeIdx)
def LandmarkAddForwardDistances(builder, forwardDistances): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(forwardDistances), 0)
def AddForwardDistances(builder, forwardDistances):
    return LandmarkAddForwardDistances(builder, forwardDistances)
def LandmarkStartForwardDistancesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartForwardDistancesVector(builder, numElems):
    return LandmarkStartForwardDistancesVector(builder, numElems)
def LandmarkAddBackwardDistances(builder, backwardDistances): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(backwardDistances), 0)
def AddBackwardDistances(builder, backwardDistances):
    return LandmarkAddBackwardDistances(builder, backwardDistances)
def LandmarkStartBackwardDistancesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBackwardDistancesVector(builder, numElems):
    return LandmarkStartBackwardDistancesVector(builder, numElems)
def LandmarkEnd(builder): return builder.EndObject()
def End(builder):
    return LandmarkEnd(builder)