# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Metadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Metadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MetadataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # Metadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Metadata
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Metadata
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Metadata
    def TraitConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Metadata
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Metadata
    def MinLat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Metadata
    def MaxLat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Metadata
    def MinLon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Metadata
    def MaxLon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def MetadataStart(builder): builder.StartObject(8)
def Start(builder):
    return MetadataStart(builder)
def MetadataAddVersion(builder, version): builder.PrependInt32Slot(0, version, 0)
def AddVersion(builder, version):
    return MetadataAddVersion(builder, version)
def MetadataAddCreatedAt(builder, createdAt): builder.PrependInt64Slot(1, createdAt, 0)
def AddCreatedAt(builder, createdAt):
    return MetadataAddCreatedAt(builder, createdAt)
def MetadataAddTraitConfig(builder, traitConfig): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(traitConfig), 0)
def AddTraitConfig(builder, traitConfig):
    return MetadataAddTraitConfig(builder, traitConfig)
def MetadataAddDescription(builder, description): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)
def AddDescription(builder, description):
    return MetadataAddDescription(builder, description)
def MetadataAddMinLat(builder, minLat): builder.PrependFloat64Slot(4, minLat, 0.0)
def AddMinLat(builder, minLat):
    return MetadataAddMinLat(builder, minLat)
def MetadataAddMaxLat(builder, maxLat): builder.PrependFloat64Slot(5, maxLat, 0.0)
def AddMaxLat(builder, maxLat):
    return MetadataAddMaxLat(builder, maxLat)
def MetadataAddMinLon(builder, minLon): builder.PrependFloat64Slot(6, minLon, 0.0)
def AddMinLon(builder, minLon):
    return MetadataAddMinLon(builder, minLon)
def MetadataAddMaxLon(builder, maxLon): builder.PrependFloat64Slot(7, maxLon, 0.0)
def AddMaxLon(builder, maxLon):
    return MetadataAddMaxLon(builder, maxLon)
def MetadataEnd(builder): return builder.EndObject()
def End(builder):
    return MetadataEnd(builder)