# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Model(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Model()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ModelBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # Model
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Model
    def Metadata(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from taro.model.Metadata import Metadata
            obj = Metadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def Topology(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from taro.model.GraphTopology import GraphTopology
            obj = GraphTopology()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def Profiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from taro.model.TemporalProfile import TemporalProfile
            obj = TemporalProfile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def ProfilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def ProfilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Model
    def TurnCosts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from taro.model.TurnCost import TurnCost
            obj = TurnCost()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def TurnCostsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def TurnCostsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Model
    def SpatialIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from taro.model.SpatialIndex import SpatialIndex
            obj = SpatialIndex()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def IdMapping(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from taro.model.IdMapping import IdMapping
            obj = IdMapping()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def Landmarks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from taro.model.Landmark import Landmark
            obj = Landmark()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
    def LandmarksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
    def LandmarksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def ModelStart(builder): builder.StartObject(7)
def Start(builder):
    return ModelStart(builder)
def ModelAddMetadata(builder, metadata): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)
def AddMetadata(builder, metadata):
    return ModelAddMetadata(builder, metadata)
def ModelAddTopology(builder, topology): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(topology), 0)
def AddTopology(builder, topology):
    return ModelAddTopology(builder, topology)
def ModelAddProfiles(builder, profiles): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(profiles), 0)
def AddProfiles(builder, profiles):
    return ModelAddProfiles(builder, profiles)
def ModelStartProfilesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartProfilesVector(builder, numElems):
    return ModelStartProfilesVector(builder, numElems)
def ModelAddTurnCosts(builder, turnCosts): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(turnCosts), 0)
def AddTurnCosts(builder, turnCosts):
    return ModelAddTurnCosts(builder, turnCosts)
def ModelStartTurnCostsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartTurnCostsVector(builder, numElems):
    return ModelStartTurnCostsVector(builder, numElems)
def ModelAddSpatialIndex(builder, spatialIndex): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(spatialIndex), 0)
def AddSpatialIndex(builder, spatialIndex):
    return ModelAddSpatialIndex(builder, spatialIndex)
def ModelAddIdMapping(builder, idMapping): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(idMapping), 0)
def AddIdMapping(builder, idMapping):
    return ModelAddIdMapping(builder, idMapping)
def ModelAddLandmarks(builder, landmarks): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(landmarks), 0)
def AddLandmarks(builder, landmarks):
    return ModelAddLandmarks(builder, landmarks)
def ModelStartLandmarksVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartLandmarksVector(builder, numElems):
    return ModelStartLandmarksVector(builder, numElems)
def ModelEnd(builder): return builder.EndObject()
def End(builder):
    return ModelEnd(builder)