# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SpatialIndex(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpatialIndex()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpatialIndex(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SpatialIndexBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # SpatialIndex
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpatialIndex
    def TreeNodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            from taro.model.KDNode import KDNode
            obj = KDNode()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SpatialIndex
    def TreeNodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpatialIndex
    def TreeNodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # SpatialIndex
    def LeafItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SpatialIndex
    def LeafItemsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # SpatialIndex
    def LeafItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpatialIndex
    def LeafItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SpatialIndex
    def RootIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def SpatialIndexStart(builder): builder.StartObject(3)
def Start(builder):
    return SpatialIndexStart(builder)
def SpatialIndexAddTreeNodes(builder, treeNodes): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(treeNodes), 0)
def AddTreeNodes(builder, treeNodes):
    return SpatialIndexAddTreeNodes(builder, treeNodes)
def SpatialIndexStartTreeNodesVector(builder, numElems): return builder.StartVector(20, numElems, 4)
def StartTreeNodesVector(builder, numElems):
    return SpatialIndexStartTreeNodesVector(builder, numElems)
def SpatialIndexAddLeafItems(builder, leafItems): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(leafItems), 0)
def AddLeafItems(builder, leafItems):
    return SpatialIndexAddLeafItems(builder, leafItems)
def SpatialIndexStartLeafItemsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartLeafItemsVector(builder, numElems):
    return SpatialIndexStartLeafItemsVector(builder, numElems)
def SpatialIndexAddRootIndex(builder, rootIndex): builder.PrependInt32Slot(2, rootIndex, 0)
def AddRootIndex(builder, rootIndex):
    return SpatialIndexAddRootIndex(builder, rootIndex)
def SpatialIndexEnd(builder): return builder.EndObject()
def End(builder):
    return SpatialIndexEnd(builder)