# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TemporalProfile(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TemporalProfile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTemporalProfile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TemporalProfileBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # TemporalProfile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TemporalProfile
    def ProfileId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TemporalProfile
    def DayMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TemporalProfile
    def Buckets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TemporalProfile
    def BucketsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # TemporalProfile
    def BucketsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TemporalProfile
    def BucketsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # TemporalProfile
    def Multiplier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def TemporalProfileStart(builder): builder.StartObject(4)
def Start(builder):
    return TemporalProfileStart(builder)
def TemporalProfileAddProfileId(builder, profileId): builder.PrependUint16Slot(0, profileId, 0)
def AddProfileId(builder, profileId):
    return TemporalProfileAddProfileId(builder, profileId)
def TemporalProfileAddDayMask(builder, dayMask): builder.PrependUint8Slot(1, dayMask, 0)
def AddDayMask(builder, dayMask):
    return TemporalProfileAddDayMask(builder, dayMask)
def TemporalProfileAddBuckets(builder, buckets): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(buckets), 0)
def AddBuckets(builder, buckets):
    return TemporalProfileAddBuckets(builder, buckets)
def TemporalProfileStartBucketsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBucketsVector(builder, numElems):
    return TemporalProfileStartBucketsVector(builder, numElems)
def TemporalProfileAddMultiplier(builder, multiplier): builder.PrependFloat32Slot(3, multiplier, 1.0)
def AddMultiplier(builder, multiplier):
    return TemporalProfileAddMultiplier(builder, multiplier)
def TemporalProfileEnd(builder): return builder.EndObject()
def End(builder):
    return TemporalProfileEnd(builder)