# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TurnCost(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TurnCost()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTurnCost(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TurnCostBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x41\x52\x4F", size_prefixed=size_prefixed)

    # TurnCost
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TurnCost
    def FromEdgeIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TurnCost
    def ToEdgeIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TurnCost
    def PenaltySeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TurnCostStart(builder): builder.StartObject(3)
def Start(builder):
    return TurnCostStart(builder)
def TurnCostAddFromEdgeIdx(builder, fromEdgeIdx): builder.PrependInt32Slot(0, fromEdgeIdx, 0)
def AddFromEdgeIdx(builder, fromEdgeIdx):
    return TurnCostAddFromEdgeIdx(builder, fromEdgeIdx)
def TurnCostAddToEdgeIdx(builder, toEdgeIdx): builder.PrependInt32Slot(1, toEdgeIdx, 0)
def AddToEdgeIdx(builder, toEdgeIdx):
    return TurnCostAddToEdgeIdx(builder, toEdgeIdx)
def TurnCostAddPenaltySeconds(builder, penaltySeconds): builder.PrependFloat32Slot(2, penaltySeconds, 0.0)
def AddPenaltySeconds(builder, penaltySeconds):
    return TurnCostAddPenaltySeconds(builder, penaltySeconds)
def TurnCostEnd(builder): return builder.EndObject()
def End(builder):
    return TurnCostEnd(builder)