services:
  - type: web
    name: taro
    runtime: docker
    plan: starter
    region: ohio
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: 10000
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0 -Dfile.encoding=UTF-8
