// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class KDNode extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public KDNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float splitValue() { return bb.getFloat(bb_pos + 0); }
  public int leftChild() { return bb.getInt(bb_pos + 4); }
  public int rightChild() { return bb.getInt(bb_pos + 8); }
  public int itemStartIndex() { return bb.getInt(bb_pos + 12); }
  public int itemCount() { return bb.getShort(bb_pos + 16) & 0xFFFF; }
  public int splitAxis() { return bb.get(bb_pos + 18) & 0xFF; }
  public int isLeaf() { return bb.get(bb_pos + 19) & 0xFF; }

  public static int createKDNode(FlatBufferBuilder builder, float splitValue, int leftChild, int rightChild, int itemStartIndex, int itemCount, int splitAxis, int isLeaf) {
    builder.prep(4, 20);
    builder.putByte((byte) isLeaf);
    builder.putByte((byte) splitAxis);
    builder.putShort((short) itemCount);
    builder.putInt(itemStartIndex);
    builder.putInt(rightChild);
    builder.putInt(leftChild);
    builder.putFloat(splitValue);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public KDNode get(int j) { return get(new KDNode(), j); }
    public KDNode get(KDNode obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

