// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Metadata extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static Metadata getRootAsMetadata(ByteBuffer _bb) { return getRootAsMetadata(_bb, new Metadata()); }
  public static Metadata getRootAsMetadata(ByteBuffer _bb, Metadata obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Metadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int version() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long createdAt() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String traitConfig() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer traitConfigAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer traitConfigInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String description() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public double minLat() { int o = __offset(12); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double maxLat() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double minLon() { int o = __offset(16); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double maxLon() { int o = __offset(18); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createMetadata(FlatBufferBuilder builder,
      int version,
      long createdAt,
      int traitConfigOffset,
      int descriptionOffset,
      double minLat,
      double maxLat,
      double minLon,
      double maxLon) {
    builder.startTable(8);
    Metadata.addMaxLon(builder, maxLon);
    Metadata.addMinLon(builder, minLon);
    Metadata.addMaxLat(builder, maxLat);
    Metadata.addMinLat(builder, minLat);
    Metadata.addCreatedAt(builder, createdAt);
    Metadata.addDescription(builder, descriptionOffset);
    Metadata.addTraitConfig(builder, traitConfigOffset);
    Metadata.addVersion(builder, version);
    return Metadata.endMetadata(builder);
  }

  public static void startMetadata(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addVersion(FlatBufferBuilder builder, int version) { builder.addInt(0, version, 0); }
  public static void addCreatedAt(FlatBufferBuilder builder, long createdAt) { builder.addLong(1, createdAt, 0L); }
  public static void addTraitConfig(FlatBufferBuilder builder, int traitConfigOffset) { builder.addOffset(2, traitConfigOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(3, descriptionOffset, 0); }
  public static void addMinLat(FlatBufferBuilder builder, double minLat) { builder.addDouble(4, minLat, 0.0); }
  public static void addMaxLat(FlatBufferBuilder builder, double maxLat) { builder.addDouble(5, maxLat, 0.0); }
  public static void addMinLon(FlatBufferBuilder builder, double minLon) { builder.addDouble(6, minLon, 0.0); }
  public static void addMaxLon(FlatBufferBuilder builder, double maxLon) { builder.addDouble(7, maxLon, 0.0); }
  public static int endMetadata(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Metadata get(int j) { return get(new Metadata(), j); }
    public Metadata get(Metadata obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

