// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Model extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static Model getRootAsModel(ByteBuffer _bb) { return getRootAsModel(_bb, new Model()); }
  public static Model getRootAsModel(ByteBuffer _bb, Model obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean ModelBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "TARO"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Model __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public org.Aayush.flatbuffers.taro.model.Metadata metadata() { return metadata(new org.Aayush.flatbuffers.taro.model.Metadata()); }
  public org.Aayush.flatbuffers.taro.model.Metadata metadata(org.Aayush.flatbuffers.taro.model.Metadata obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public org.Aayush.flatbuffers.taro.model.GraphTopology topology() { return topology(new org.Aayush.flatbuffers.taro.model.GraphTopology()); }
  public org.Aayush.flatbuffers.taro.model.GraphTopology topology(org.Aayush.flatbuffers.taro.model.GraphTopology obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public org.Aayush.flatbuffers.taro.model.TemporalProfile profiles(int j) { return profiles(new org.Aayush.flatbuffers.taro.model.TemporalProfile(), j); }
  public org.Aayush.flatbuffers.taro.model.TemporalProfile profiles(org.Aayush.flatbuffers.taro.model.TemporalProfile obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int profilesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public org.Aayush.flatbuffers.taro.model.TemporalProfile.Vector profilesVector() { return profilesVector(new org.Aayush.flatbuffers.taro.model.TemporalProfile.Vector()); }
  public org.Aayush.flatbuffers.taro.model.TemporalProfile.Vector profilesVector(org.Aayush.flatbuffers.taro.model.TemporalProfile.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.Aayush.flatbuffers.taro.model.TurnCost turnCosts(int j) { return turnCosts(new org.Aayush.flatbuffers.taro.model.TurnCost(), j); }
  public org.Aayush.flatbuffers.taro.model.TurnCost turnCosts(org.Aayush.flatbuffers.taro.model.TurnCost obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int turnCostsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public org.Aayush.flatbuffers.taro.model.TurnCost.Vector turnCostsVector() { return turnCostsVector(new org.Aayush.flatbuffers.taro.model.TurnCost.Vector()); }
  public org.Aayush.flatbuffers.taro.model.TurnCost.Vector turnCostsVector(org.Aayush.flatbuffers.taro.model.TurnCost.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public org.Aayush.flatbuffers.taro.model.SpatialIndex spatialIndex() { return spatialIndex(new org.Aayush.flatbuffers.taro.model.SpatialIndex()); }
  public org.Aayush.flatbuffers.taro.model.SpatialIndex spatialIndex(org.Aayush.flatbuffers.taro.model.SpatialIndex obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public org.Aayush.flatbuffers.taro.model.IdMapping idMapping() { return idMapping(new org.Aayush.flatbuffers.taro.model.IdMapping()); }
  public org.Aayush.flatbuffers.taro.model.IdMapping idMapping(org.Aayush.flatbuffers.taro.model.IdMapping obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public org.Aayush.flatbuffers.taro.model.Landmark landmarks(int j) { return landmarks(new org.Aayush.flatbuffers.taro.model.Landmark(), j); }
  public org.Aayush.flatbuffers.taro.model.Landmark landmarks(org.Aayush.flatbuffers.taro.model.Landmark obj, int j) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int landmarksLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public org.Aayush.flatbuffers.taro.model.Landmark.Vector landmarksVector() { return landmarksVector(new org.Aayush.flatbuffers.taro.model.Landmark.Vector()); }
  public org.Aayush.flatbuffers.taro.model.Landmark.Vector landmarksVector(org.Aayush.flatbuffers.taro.model.Landmark.Vector obj) { int o = __offset(16); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createModel(FlatBufferBuilder builder,
      int metadataOffset,
      int topologyOffset,
      int profilesOffset,
      int turnCostsOffset,
      int spatialIndexOffset,
      int idMappingOffset,
      int landmarksOffset) {
    builder.startTable(7);
    Model.addLandmarks(builder, landmarksOffset);
    Model.addIdMapping(builder, idMappingOffset);
    Model.addSpatialIndex(builder, spatialIndexOffset);
    Model.addTurnCosts(builder, turnCostsOffset);
    Model.addProfiles(builder, profilesOffset);
    Model.addTopology(builder, topologyOffset);
    Model.addMetadata(builder, metadataOffset);
    return Model.endModel(builder);
  }

  public static void startModel(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addMetadata(FlatBufferBuilder builder, int metadataOffset) { builder.addOffset(0, metadataOffset, 0); }
  public static void addTopology(FlatBufferBuilder builder, int topologyOffset) { builder.addOffset(1, topologyOffset, 0); }
  public static void addProfiles(FlatBufferBuilder builder, int profilesOffset) { builder.addOffset(2, profilesOffset, 0); }
  public static int createProfilesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProfilesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTurnCosts(FlatBufferBuilder builder, int turnCostsOffset) { builder.addOffset(3, turnCostsOffset, 0); }
  public static int createTurnCostsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTurnCostsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSpatialIndex(FlatBufferBuilder builder, int spatialIndexOffset) { builder.addOffset(4, spatialIndexOffset, 0); }
  public static void addIdMapping(FlatBufferBuilder builder, int idMappingOffset) { builder.addOffset(5, idMappingOffset, 0); }
  public static void addLandmarks(FlatBufferBuilder builder, int landmarksOffset) { builder.addOffset(6, landmarksOffset, 0); }
  public static int createLandmarksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLandmarksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endModel(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishModelBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "TARO"); }
  public static void finishSizePrefixedModelBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "TARO"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Model get(int j) { return get(new Model(), j); }
    public Model get(Model obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

