// automatically generated by the FlatBuffers compiler, do not modify

package org.Aayush.flatbuffers.taro.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SpatialIndex extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static SpatialIndex getRootAsSpatialIndex(ByteBuffer _bb) { return getRootAsSpatialIndex(_bb, new SpatialIndex()); }
  public static SpatialIndex getRootAsSpatialIndex(ByteBuffer _bb, SpatialIndex obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SpatialIndex __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public KDNode treeNodes(int j) { return treeNodes(new KDNode(), j); }
  public KDNode treeNodes(KDNode obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 20, bb) : null; }
  public int treeNodesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public KDNode.Vector treeNodesVector() { return treeNodesVector(new KDNode.Vector()); }
  public KDNode.Vector treeNodesVector(KDNode.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 20, bb) : null; }
  public int leafItems(int j) { int o = __offset(6); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int leafItemsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public IntVector leafItemsVector() { return leafItemsVector(new IntVector()); }
  public IntVector leafItemsVector(IntVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer leafItemsAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer leafItemsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }
  public int rootIndex() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createSpatialIndex(FlatBufferBuilder builder,
      int treeNodesOffset,
      int leafItemsOffset,
      int rootIndex) {
    builder.startTable(3);
    SpatialIndex.addRootIndex(builder, rootIndex);
    SpatialIndex.addLeafItems(builder, leafItemsOffset);
    SpatialIndex.addTreeNodes(builder, treeNodesOffset);
    return SpatialIndex.endSpatialIndex(builder);
  }

  public static void startSpatialIndex(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addTreeNodes(FlatBufferBuilder builder, int treeNodesOffset) { builder.addOffset(0, treeNodesOffset, 0); }
  public static void startTreeNodesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(20, numElems, 4); }
  public static void addLeafItems(FlatBufferBuilder builder, int leafItemsOffset) { builder.addOffset(1, leafItemsOffset, 0); }
  public static int createLeafItemsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startLeafItemsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRootIndex(FlatBufferBuilder builder, int rootIndex) { builder.addInt(2, rootIndex, 0); }
  public static int endSpatialIndex(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SpatialIndex get(int j) { return get(new SpatialIndex(), j); }
    public SpatialIndex get(SpatialIndex obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

